### ISSUE TITLE
Traduire les exemples de warnings d'accessibilité ?

### ISSUE THREAD

**Issue by bleucitron** [iOiurson/svelte-fr-docs#69]
Actuellement nous traduisons les commentaires d'exemples dans la partie `06-accessibility-warnings` :

```sv
<!-- A11y: <textarea> ne peut pas avoir le rôle 'listitem' -->
<textarea role="listitem" />
```

Le problème c'est qu'en pratique ces warnings seront de toutes façons affichés en anglais.

Avec ça en tête, ne faudrait-il pas les laisser en anglais dans la doc française ?

**Comment by Ennoriel** [comment]
Ah, j'ai vu le problème sur la relecture de la PR pour corriger les issues. Moi je suis d'avis de les laisser en anglais. Après, on peut éventuellement mettre les deux versions

**Comment by bleucitron** [comment]
Je les ai laissé en anglais au final.
